expert_administration:
    resource: "@ExpertAdministrationBundle/Resources/config/routing.yml"
    prefix:   /

administration_acceuil:
    resource: "@ExpertAcceuilBundle/Resources/config/routing.yml"
    prefix:   /

administration_user:
    resource: "@ExpertUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

