administration_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: AdministrationUserBundle:Default:index }

administration_user_add:
    path:     /sign-up
    defaults: { _controller: AdministrationUserBundle:Default:signUp }

